[package]
name = "chippy8"
version = "0.1.0"
authors = ["felang"]
edition = "2018"

[dependencies]
rand = "0.7.0"
glium = "*"
imgui = "0.1.0"
imgui-glium-renderer = "0.1.0"
imgui-winit-support = "0.1.0"